# list file names for a run
globals:
  filenames:
    Param: Param
    Assump: Assump
    AssetAltBondAssump: AssetAltBondAssump
    AssetAltBondDistByRatingByTerm: AssetAltBondDistByRatingByTerm
    AssetTradBondAssump: AssetTradBondAssump
    AssetTradBondDistByRatingByTerm: AssetTradBondDistByRatingByTerm
    RF_Curves: RF_Curves
    SAA_Sims: SAA_Sims
    StressBondSpdByRatingByTerm: StressBondSpdByRatingByTerm