# format: indent by 3 spaces
names:
  - CALENDAR_MTH
  - CALENDAR_YR
  - CALENDAR_DATE
  - TEST_ARRAY
  - TEST_ARRAY_NEW
  - RC_FAC_HKD
  - RC_FAC_USD
  - ASSET_MIX
  - TRAD_BOND_DIST
  - TRAD_BOND_DUR
  - ALT_BOND_DIST
  - ALT_BOND_DUR
  - TRAD_BOND_MIX_BY_TERM
  - ALT_BOND_MIX_BY_TERM
  - BOND_DUR
  - BOND_DUR_INT
  - INT_RISK_SCAL
  - RF_ECON_SCENARIO
  - STRESS_BOND_SPD_PARAMS
  - NAR_TOT
  - NAR_FI
  - NAR_EQ
  - NAR_PROP
  - TOT_NAR
  - BOND_TRAD
  - BOND_ALT
  - PIVOT_RC_SPD_BOND_TRAD
  - PIVOT_RC_SPD_BOND_ALT
  - PIVOT_RC_SPD_BOND
  - RC_ASSET_EQ
  - RC_ASSET_PROP
  - ASSET_BAL
  - ASSET_RETURN_RATE
  - ASSET_SD_RATE
  - ASSET_HKD_MIX
  - ASSET_USD_MIX
  - NAR_TOT_HKD
  - NAR_TOT_USD
  - NAR_FI_HKD
  - NAR_FI_USD
  - SUM_NAR_FI_HKD
  - SUM_NAR_FI_USD
  - HKD_BOND_MV_CHG
  - USD_BOND_MV_CHG
  - PORT_BOND_MV
  - PORT_BOND_MV_CHG
  - PORT_NAR_HKD
  - PORT_NAR_USD
  - PORT_RETURN_RATE
  - PORT_RISK
  - PCR_FX
  - PCR_EQ
  - PCR_PROP
  - PCR_SPD
  - PCR_INT
  - PCR_MKT_RISK
  - PCR_TOTAL
  - TEST_STR_VAR
  - TEST_ARRAY_TXT
